### ISSUE TITLE
Will support Android?

### ISSUE THREAD

**Issue by ayakasuki** [NekoTarou/lskypro-auto-upload#3]
As shown in the topic, I want to ask can support android, the plug-in in PC support, android display does not support your device

**Comment by NekoTarou** [comment]
插件里有用到只支持PC的接口，因此目前是不支持移动端的。而且考虑到图片上传的需求在移动端并不好操作，所以近期不会支持。
后续如果项目不忙了或许可以研究一下，抱歉。
