### ISSUE TITLE
无法自动上传图片链接里的图片

### ISSUE THREAD

**Issue by itcbx** [NekoTarou/lskypro-auto-upload#4]
我看了下代码，功能上本意是支持的，但是实际上如果粘贴的内容里有markdown格式的网络图片链接，这个插件是无法自动上传的，主要是createFileObjectFromPath里面的`var obsfile = _this.app.vault.getAbstractFileByPath(path);`这个语句，如果path是网络链接，返回的obsfile的值为空，导致后续的操作无法进行，这个app.vault.getAbstractFileByPath应该是主要用于本地图片地址，网络地址应该是不行的

**Comment by NekoTarou** [comment]
@gaojunxin

**Comment by gaojunxin** [comment]
@itcbx @NekoTarou 已修复

**Comment by itcbx** [comment]
fetch方式获取远程图片，会出现域问题无法正常获取，建议用以下方法：
```
if(path.startsWith('https://') || path.startsWith('http://')){
    return requestUrl(path).then(response => {
        var blob = new Blob([response.arrayBuffer]);
        resolve(new File([blob], path.split("/").pop()));
    });
}
```
