### ISSUE TITLE
一直跑不通，不知道原因在哪里

### ISSUE THREAD

**Issue by 954708775** [NekoTarou/lskypro-auto-upload#7]
我的lsky是通过nas的docker创建的，因此lsky的域名是本地ip加端口，是不是因为这个原因导制的无法使用呢

**Comment by NekoTarou** [comment]
插件本身是没有限制的，我这边也是用Nas的docker部署，然后把端口映射到公网上使用的。
只要插件上配置的地址是通的就可以使用。尽量把端口映射出来吧。

**Comment by 954708775** [comment]
你好，

所以是需要进行端口映射到公网这一个操作是吧，我去研究一下。
感谢。

Benny

**Comment by NekoTarou** [comment]
首先本地保证本地能够正常访问，是否映射到公网看你的使用需求，如果不需要公网使用，内网访问即可。建议使用域名，这样以后换机器就不用考虑迁移的问题了
